SELECT ID, EMAIL, PASSWORD, NAME, REGDATE
  FROM MEMBER;

SELECT ID, EMAIL, PASSWORD, NAME, REGDATE
  FROM MEMBER
 WHERE EMAIL = 'test@test.co.kr';

UPDATE MEMBER
   SET PASSWORD = '2222',
       NAME = 'test44'
 WHERE EMAIL = 'test33@test.co.kr';

INSERT INTO MEMBER(EMAIL, PASSWORD, NAME, REGDATE)
VALUES ('test33@test.co.kr', '1234', 'test33', sysdate);

DELETE
  FROM MEMBER
 WHERE EMAIL = 'test33@test.co.kr';

SELECT ID, EMAIL, PASSWORD, NAME, REGDATE
  FROM MEMBER
 WHERE REGDATE BETWEEN '2020-09-01' AND '2020-09-30'
 ORDER BY REGDATE DESC;
